### ISSUE TITLE
Fix Selenium instructions link in contributing.md and link it in README

### ISSUE THREAD

**Issue by alshakero** [StarcounterApps/KitchenSink#138]
Correct instructions link: https://docs.starcounter.io/guides/web-apps/acceptance-testing-with-selenium/

**Comment by alshakero** [comment]
Fixed by https://github.com/StarcounterApps/KitchenSink/pull/139

**Comment by warpech** [comment]
Thanks for reporting, but this needs more work. #139 did not fix the URL, it is still the old one. Also, that PR added a typo: `Contrinbuting` in `README.md`

**Comment by warpech** [comment]
Sorry, just noticed that you fixed that later in https://github.com/StarcounterApps/KitchenSink/commit/044cd07455d850724316a659e1bc0f40b425973c#diff-6a3371457528722a734f3c51d9238c13.

**Comment by alshakero** [comment]
@warpech it's just a preference issue. I skimmed the readme expecting CONTRIBUTING as I am used to [jsonpatch](https://github.com/Starcounter-Jack/JSON-Patch#contributing) and [JSONPatcherProxy](https://github.com/Palindrom/JSONPatcherProxy#contributing) and thought it wasn't there because it had a different style. So I thought adding both options would make life easier. 

Would you like me to remove it? Or fix the typo.

**Comment by warpech** [comment]
I don't know, I'd just prefer to have it everywhere in the same way. @Mackiovello any opinion on this?
